In [58]:
import tensorflow as tf
import numpy as np
import pandas as pd
from tensorflow.keras.layers import Dense
from tensorflow.keras import Sequential
from tensorflow.keras.optimizers import Adam
from sklearn import datasets
import matplotlib.pyplot as plt
import seaborn as sns

In [92]:
titanic = sns.load_dataset("titanic")
titanic

survived  pclass     sex   age  sibsp  parch     fare embarked   class  \
0           0       3    male  22.0      1      0   7.2500        S   Third   
1           1       1  female  38.0      1      0  71.2833        C   First   
2           1       3  female  26.0      0      0   7.9250        S   Third   
3           1       1  female  35.0      1      0  53.1000        S   First   
4           0       3    male  35.0      0      0   8.0500        S   Third   
..        ...     ...     ...   ...    ...    ...      ...      ...     ...   
886         0       2    male  27.0      0      0  13.0000        S  Second   
887         1       1  female  19.0      0      0  30.0000        S   First   
888         0       3  female   NaN      1      2  23.4500        S   Third   
889         1       1    male  26.0      0      0  30.0000        C   First   
890         0       3    male  32.0      0      0   7.7500        Q   Third   

       who  adult_male deck  embark_town alive  alone  
0      man        True  NaN  Southampton    no  False  
1    woman       False    C    Cherbourg   yes  False  
2    woman       False  NaN  Southampton   yes   True  
3    woman       False    C  Southampton   yes  False  
4      man        True  NaN  Southampton    no   True  
..     ...         ...  ...          ...   ...    ...  
886    man        True  NaN  Southampton    no   True  
887  woman       False    B  Southampton   yes   True  
888  woman       False  NaN  Southampton    no  False  
889    man        True    C    Cherbourg   yes   True  
890    man        True  NaN   Queenstown    no   True  

[891 rows x 15 columns]

In [102]:
titanic.loc[titanic["sex"] == "male", "Sex_encode"] = 0
titanic.loc[titanic["sex"] == "female", "Sex_encode"] = 1
titanic

survived  pclass     sex   age  sibsp  parch     fare embarked   class  \
0           0       3    male  22.0      1      0   7.2500        S   Third   
1           1       1  female  38.0      1      0  71.2833        C   First   
2           1       3  female  26.0      0      0   7.9250        S   Third   
3           1       1  female  35.0      1      0  53.1000        S   First   
4           0       3    male  35.0      0      0   8.0500        S   Third   
..        ...     ...     ...   ...    ...    ...      ...      ...     ...   
886         0       2    male  27.0      0      0  13.0000        S  Second   
887         1       1  female  19.0      0      0  30.0000        S   First   
888         0       3  female   NaN      1      2  23.4500        S   Third   
889         1       1    male  26.0      0      0  30.0000        C   First   
890         0       3    male  32.0      0      0   7.7500        Q   Third   

       who  adult_male deck  embark_town alive  alone  male  female  \
0      man        True  NaN  Southampton    no  False   NaN     NaN   
1    woman       False    C    Cherbourg   yes  False   NaN     NaN   
2    woman       False  NaN  Southampton   yes   True   NaN     NaN   
3    woman       False    C  Southampton   yes  False   NaN     NaN   
4      man        True  NaN  Southampton    no   True   NaN     NaN   
..     ...         ...  ...          ...   ...    ...   ...     ...   
886    man        True  NaN  Southampton    no   True   NaN     NaN   
887  woman       False    B  Southampton   yes   True   NaN     NaN   
888  woman       False  NaN  Southampton    no  False   NaN     NaN   
889    man        True    C    Cherbourg   yes   True   NaN     NaN   
890    man        True  NaN   Queenstown    no   True   NaN     NaN   

     Sex_encode  
0           0.0  
1           1.0  
2           1.0  
3           1.0  
4           0.0  
..          ...  
886         0.0  
887         1.0  
888         1.0  
889         0.0  
890         0.0  

[891 rows x 18 columns]

In [112]:
xdata = titanic[['Sex_encode','fare']]
ydata = titanic['survived']
xdata

Sex_encode     fare
0           0.0   7.2500
1           1.0  71.2833
2           1.0   7.9250
3           1.0  53.1000
4           0.0   8.0500
..          ...      ...
886         0.0  13.0000
887         1.0  30.0000
888         1.0  23.4500
889         0.0  30.0000
890         0.0   7.7500

[891 rows x 2 columns]

# Tensor

In [136]:
x = tf.placeholder(tf.float32,shape=[None,2] )
y = tf.constant( ydata, tf.float32)

In [137]:
w = tf.Variable( tf.random_uniform([2,1]) )
b = tf.Variable( tf.random_uniform([1]) )

In [138]:
z = tf.matmul(x,w) + b
hx = tf.nn.sigmoid( z )

In [139]:
cost_i = y*(-tf.log(hx))+(1-y)*(-tf.log(1-hx))
cost = tf.reduce_mean( cost_i )

In [140]:
optimizer = tf.train.GradientDescentOptimizer( 0.01 )
train = optimizer.minimize( cost )
sess = tf.Session()
init =tf.global_variables_initializer()
sess.run( init)

In [133]:
for i in range(1001):
    sess.run( train, {x:xdata})
    if i%100==0:
        print( i, sess.run(cost, {x:xdata}))

0 nan
1 nan
2 nan
3 nan
4 nan
5 nan
6 nan
7 nan
8 nan
9 nan
10 nan
11 nan
12 nan
13 nan
14 nan
15 nan
16 nan
17 nan
18 nan
19 nan
20 nan
21 nan
22 nan
23 nan
24 nan
25 nan
26 nan
27 nan
28 nan
29 nan
30 nan
31 nan
32 nan
33 nan
34 nan
35 nan
36 nan
37 nan
38 nan
39 nan
40 nan
41 nan
42 nan
43 nan
44 nan
45 nan
46 nan
47 nan
48 nan
49 nan
50 nan
51 nan
52 nan
53 nan
54 nan
55 nan
56 nan
57 nan
58 nan
59 nan
60 nan
61 nan
62 nan
63 nan
64 nan
65 nan
66 nan
67 nan
68 nan
69 nan
70 nan
71 nan
72 nan
73 nan
74 nan
75 nan
76 nan
77 nan
78 nan
79 nan
80 nan
81 nan
82 nan
83 nan
84 nan
85 nan
86 nan
87 nan
88 nan
89 nan
90 nan
91 nan
92 nan
93 nan
94 nan
95 nan
96 nan
97 nan
98 nan
99 nan
100 nan
101 nan
102 nan
103 nan
104 nan
105 nan
106 nan
107 nan
108 nan
109 nan
110 nan
111 nan
112 nan
113 nan
114 nan
115 nan
116 nan
117 nan
118 nan
119 nan
120 nan
121 nan
122 nan
123 nan
124 nan
125 nan
126 nan
127 nan
128 nan
129 nan
130 nan
131 nan
132 nan
133 nan
134 nan
135 nan
136 nan
137 nan
138 na

KeyboardInterrupt: 

In [142]:
sess.run( w)

array([[0.05213773],
       [0.02700281]], dtype=float32)

In [143]:
sess.run(b)

array([0.37987185], dtype=float32)

In [146]:
result = sess.run( hx, {x:[[0,53]]})

In [147]:
result>0.5

array([[ True]])

# Keras

In [111]:
IO = Dense( units=1, input_dim=2,activation='sigmoid' )
model = Sequential( [IO])
model.compile( loss='binary_crossentropy',
              optimizer=Adam(0.1), metrics=['accuracy'] )
h = model.fit( xdata,ydata, epochs=1000)

Train on 891 samples
Epoch 1/1000
891/891 [==============================] - 0s 97us/sample - loss: 3.9350 - acc: 0.5544
Epoch 2/1000
891/891 [==============================] - 0s 29us/sample - loss: 0.6978 - acc: 0.6835
Epoch 3/1000
891/891 [==============================] - 0s 30us/sample - loss: 0.5538 - acc: 0.7565
Epoch 4/1000
891/891 [==============================] - 0s 34us/sample - loss: 0.6409 - acc: 0.7475
Epoch 5/1000
891/891 [==============================] - 0s 35us/sample - loss: 0.6592 - acc: 0.7419
Epoch 6/1000
891/891 [==============================] - 0s 31us/sample - loss: 0.5289 - acc: 0.7800
Epoch 7/1000
891/891 [==============================] - 0s 24us/sample - loss: 0.5471 - acc: 0.7755
Epoch 8/1000
891/891 [==============================] - 0s 27us/sample - loss: 0.5096 - acc: 0.7811
Epoch 9/1000
891/891 [==============================] - 0s 35us/sample - loss: 0.5973 - acc: 0.7609
Epoch 10/1000
891/891 [==============================] - 0s 32us/sample - loss:

In [124]:
example = model.predict(np.array([[0,53]]))

In [126]:
model.predict_classes(np.array([[0,53]]))

array([[0]])

In [117]:
h.history['acc'][-1]

0.7811448

In [141]:
IO.get_weights()

[array([[2.689544  ],
        [0.01163268]], dtype=float32),
 array([-1.9606318], dtype=float32)]