In [2]:
import tensorflow as tf 
import matplotlib.pyplot as plt  
import numpy as np
import pandas as pd 
from tensorflow.keras.layers import Dense
from tensorflow.keras import Sequential
from tensorflow.keras.optimizers import Adam
import seaborn as sns

In [3]:
titanic = sns.load_dataset("titanic")

In [4]:
titanic

survived  pclass     sex   age  sibsp  parch     fare embarked   class  \
0           0       3    male  22.0      1      0   7.2500        S   Third   
1           1       1  female  38.0      1      0  71.2833        C   First   
2           1       3  female  26.0      0      0   7.9250        S   Third   
3           1       1  female  35.0      1      0  53.1000        S   First   
4           0       3    male  35.0      0      0   8.0500        S   Third   
..        ...     ...     ...   ...    ...    ...      ...      ...     ...   
886         0       2    male  27.0      0      0  13.0000        S  Second   
887         1       1  female  19.0      0      0  30.0000        S   First   
888         0       3  female   NaN      1      2  23.4500        S   Third   
889         1       1    male  26.0      0      0  30.0000        C   First   
890         0       3    male  32.0      0      0   7.7500        Q   Third   

       who  adult_male deck  embark_town alive  alone  
0      man        True  NaN  Southampton    no  False  
1    woman       False    C    Cherbourg   yes  False  
2    woman       False  NaN  Southampton   yes   True  
3    woman       False    C  Southampton   yes  False  
4      man        True  NaN  Southampton    no   True  
..     ...         ...  ...          ...   ...    ...  
886    man        True  NaN  Southampton    no   True  
887  woman       False    B  Southampton   yes   True  
888  woman       False  NaN  Southampton    no  False  
889    man        True    C    Cherbourg   yes   True  
890    man        True  NaN   Queenstown    no   True  

[891 rows x 15 columns]

- fare(승선가격), 성별에 따른 생존유무를 예측하시오
- 남성, 53 달러인 경우 생존 유무를 예측하시오
- w, b를 구하고, 정확도를 구하시오 (텐서, 케라스)

In [5]:
df = titanic[['sex','fare','survived']]
# df['winning_rate'] = df.apply(lambda x:relative_record(x['team'], x['against'])[3], axis=1)

In [6]:
def sex(x):
    if x == 'male':
        return(1)
    else:
        return(0)

In [7]:
df['sex'] = df.apply(lambda x: sex(x['sex']), axis=1)

C:\Users\user\anaconda3\lib\site-packages\ipykernel_launcher.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """Entry point for launching an IPython kernel.


In [8]:
# 정규화

from sklearn import preprocessing

scale = preprocessing.MinMaxScaler()
dataN = scale.fit_transform(df)


In [9]:
df

sex     fare  survived
0      1   7.2500         0
1      0  71.2833         1
2      0   7.9250         1
3      0  53.1000         1
4      1   8.0500         0
..   ...      ...       ...
886    1  13.0000         0
887    0  30.0000         1
888    0  23.4500         0
889    1  30.0000         1
890    1   7.7500         0

[891 rows x 3 columns]

In [10]:
xdata = dataN[:,:-1]
ydata = dataN[:,[-1]]

In [11]:
x = tf.placeholder(tf.float32, shape=[None,2])
y = tf.constant(ydata, tf.float32)

In [12]:
w = tf.Variable(tf.random_uniform([2,1]))
b = tf.Variable(tf.random_uniform([1]))

In [13]:
z = tf.matmul(x,w) + b
hx = tf.nn.sigmoid(z)

In [14]:
cost_i = y*(-tf.log(hx)) + (1-y)*(-tf.log(1-hx))
cost = tf.reduce_mean(cost_i)

In [15]:
optimizer = tf.train.GradientDescentOptimizer(0.001)
train = optimizer.minimize(cost)

In [16]:
sess = tf.Session()
init = tf.global_variables_initializer()
sess.run(init)

In [17]:
predict = tf.cast(hx>0.5, dtype = tf.float32)
accuracy = tf.reduce_mean(tf.cast(tf.equal(predict, y), dtype = tf.float32))

In [20]:
for i in range(100000):
    sess.run(train, {x:xdata})
    if i % 1000 == 0:
        print(sess.run(accuracy, {x:xdata}))

0.7890011
0.7890011
0.7890011
0.7890011
0.7890011
0.7890011
0.7890011
0.7890011
0.7890011
0.7890011
0.7890011
0.7890011
0.7890011
0.7890011
0.7890011
0.7890011
0.7890011
0.7890011
0.7890011
0.7890011
0.7890011
0.7890011
0.7890011
0.7890011
0.7890011
0.7890011
0.7890011
0.7890011
0.7890011
0.7890011
0.7890011
0.7890011
0.7890011
0.7890011
0.7890011
0.7890011
0.7890011
0.7890011
0.7890011
0.7890011
0.7890011
0.7890011
0.7890011
0.7890011
0.7890011
0.7890011
0.7890011
0.7890011
0.7890011
0.7890011
0.7890011
0.7890011
0.7890011
0.7890011
0.7890011
0.7890011
0.7890011
0.7890011
0.7890011
0.7890011
0.7890011
0.7890011
0.7890011
0.7890011
0.7890011
0.7890011
0.7890011
0.7890011
0.7890011
0.7890011
0.7890011
0.7890011
0.7890011
0.7890011
0.7890011
0.7890011
0.7890011
0.7890011
0.7890011
0.7890011
0.7890011
0.7890011
0.7890011
0.7890011
0.7890011
0.7890011
0.7890011
0.7890011
0.7890011
0.7890011
0.7890011
0.7890011
0.7890011
0.7890011
0.7890011
0.7890011
0.7890011
0.7890011
0.7890011
0.7890011


In [21]:
sess.run(b)

array([0.8919054], dtype=float32)

In [22]:
a = sess.run(hx, {x: xdata})

In [23]:
import pandas as pd

In [24]:
dict = {'answer': ydata, 'predict':a}

In [26]:
df = pd.Dataframe(dict)

AttributeError: module 'pandas' has no attribute 'Dataframe'

In [27]:
sess.run(predict, {x: [[1,53]]})

array([[1.]], dtype=float32)

In [28]:
labelScale = preprocessing.MinMaxScaler()
y1 = labelScale.fit_transform(df.iloc[:,[-1]])

In [29]:
labelScale.inverse_transform([[1]])

array([[1.]])

# 케라스 이용

In [30]:
IO = Dense(units = 1, input_dim = 2, activation = 'sigmoid')
model = Sequential(IO)
model.compile(loss = 'binary_crossentropy', optimizer = Adam(0.1), metrics = ['accuracy'] )
h = model.fit(xdata, ydata, epochs = 1000)

Instructions for updating:
If using Keras pass *_constraint arguments to layers.
Instructions for updating:
Use tf.where in 2.0, which has the same broadcast rule as np.where
Train on 891 samples
Epoch 1/1000
891/891 [==============================] - 0s 107us/sample - loss: 0.6917 - acc: 0.5376
Epoch 2/1000
891/891 [==============================] - 0s 27us/sample - loss: 0.5354 - acc: 0.7733
Epoch 3/1000
891/891 [==============================] - 0s 28us/sample - loss: 0.5015 - acc: 0.7834
Epoch 4/1000
891/891 [==============================] - 0s 28us/sample - loss: 0.4986 - acc: 0.7845
Epoch 5/1000
891/891 [==============================] - 0s 30us/sample - loss: 0.4997 - acc: 0.7823
Epoch 6/1000
891/891 [==============================] - 0s 22us/sample - loss: 0.5028 - acc: 0.7823
Epoch 7/1000
891/891 [==============================] - 0s 27us/sample - loss: 0.4986 - acc: 0.7823
Epoch 8/1000
891/891 [==============================] - 0s 25us/sample - loss: 0.4997 - acc: 0.7823
Epo

In [31]:
h.history['acc'][-1]

0.7811448

In [32]:
model.predict(np.array([[1,53]]))

array([[1.]], dtype=float32)