In [1]:
# 1. trees.csv를 읽어들여서 아래에 대해
#  Volume을 예측해 보세요.(텐서, 케라스)
# Girth 8.8, 10.5
# Height 63, 72

# 2. volume이 40 이상이면 크다
# 30이상이면 보통 미만이면 적음으로
# 아래와 같이 출력하시요
# volume  정도
# ============
#  10.3    적음
# ...

# 3. Height  가 가장 작은값과 큰값을
# 구하시요

# 4. girth(테두리) 가 가장큰 top5를
# 출력하세요(girth, height, volume)
 

# 첫번째 문제

In [2]:
import tensorflow as tf
import numpy as np
import pandas as pd
from sklearn import datasets
import matplotlib.pyplot as plt

from sklearn import preprocessing
from tensorflow.keras.layers import Dense
from tensorflow.keras import Sequential
from tensorflow.keras.optimizers import Adam



In [3]:
data = pd.read_csv('trees.csv')
data.columns=['Girth','Height','Volume']
data

Girth  Height  Volume
0     8.3      70    10.3
1     8.6      65    10.3
2     8.8      63    10.2
3    10.5      72    16.4
4    10.7      81    18.8
5    10.8      83    19.7
6    11.0      66    15.6
7    11.0      75    18.2
8    11.1      80    22.6
9    11.2      75    19.9
10   11.3      79    24.2
11   11.4      76    21.0
12   11.4      76    21.4
13   11.7      69    21.3
14   12.0      75    19.1
15   12.9      74    22.2
16   12.9      85    33.8
17   13.3      86    27.4
18   13.7      71    25.7
19   13.8      64    24.9
20   14.0      78    34.5
21   14.2      80    31.7
22   14.5      74    36.3
23   16.0      72    38.3
24   16.3      77    42.6
25   17.3      81    55.4
26   17.5      82    55.7
27   17.9      80    58.3
28   18.0      80    51.5
29   18.0      80    51.0
30   20.6      87    77.0

In [4]:
data = np.float32(data)

#### 정규화

In [5]:
scale = preprocessing.MinMaxScaler()
dataN = scale.fit_transform(data)
dataN

array([[0.        , 0.29166675, 0.00149702],
       [0.02439022, 0.08333349, 0.00149702],
       [0.04065037, 0.        , 0.        ],
       [0.17886174, 0.375     , 0.09281437],
       [0.19512188, 0.75      , 0.1287425 ],
       [0.20325202, 0.8333335 , 0.1422156 ],
       [0.21951216, 0.125     , 0.08083834],
       [0.21951216, 0.5       , 0.1197605 ],
       [0.22764224, 0.7083335 , 0.18562876],
       [0.23577231, 0.5       , 0.14520957],
       [0.24390239, 0.66666675, 0.20958085],
       [0.25203246, 0.54166675, 0.16167666],
       [0.25203246, 0.54166675, 0.16766466],
       [0.27642268, 0.25      , 0.16616766],
       [0.30081296, 0.5       , 0.13323353],
       [0.37398368, 0.4583335 , 0.17964073],
       [0.37398368, 0.91666675, 0.35329342],
       [0.40650398, 0.9583335 , 0.25748503],
       [0.43902427, 0.3333335 , 0.23203595],
       [0.44715446, 0.04166675, 0.22005989],
       [0.4634146 , 0.625     , 0.36377245],
       [0.47967476, 0.7083335 , 0.32185632],
       [0.

In [6]:
xdata = dataN[:,:-1]
ydata = dataN[:,[-1]]

In [11]:
x = tf.placeholder(tf.float32, shape=[None,2])
y = tf.constant(ydata, tf.float32)

w = tf.Variable(tf.random_uniform([2,1]))
b = tf.Variable(tf.random_uniform([1]))

hx = tf.matmul(x,w) +b
cost = tf.reduce_mean( tf.square(hx-y) )

optimizer = tf.train.AdamOptimizer( 0.001 )
train = optimizer.minimize( cost )
sess = tf.Session()
init = tf.global_variables_initializer()
sess.run(init)
for i in range(10000):
    sess.run(train, {x:xdata})
#     print(i,sess.run(cost, {x:xdata}))

In [12]:
sess.run(w)

array([[0.86692166],
       [0.12188675]], dtype=float32)

In [13]:
sess.run(b)

array([-0.11582478], dtype=float32)

In [17]:
labelScale = preprocessing.MinMaxScaler()
y1 = labelScale.fit_transform(data[:,[-1]])

In [18]:
arr = scale.transform([[8.8,63],[10.3,72]])
arr[:,:-1]

ValueError: operands could not be broadcast together with shapes (2,2) (3,) (2,2) 

In [13]:
data[:,[-1]]

array([[10.3],
       [10.3],
       [10.2],
       [16.4],
       [18.8],
       [19.7],
       [15.6],
       [18.2],
       [22.6],
       [19.9],
       [24.2],
       [21. ],
       [21.4],
       [21.3],
       [19.1],
       [22.2],
       [33.8],
       [27.4],
       [25.7],
       [24.9],
       [34.5],
       [31.7],
       [36.3],
       [38.3],
       [42.6],
       [55.4],
       [55.7],
       [58.3],
       [51.5],
       [51. ],
       [77. ]], dtype=float32)

In [ ]:
labelScale = preprocessing.MinMaxScaler()
y1 = labelScale.fit_transform(data[:,[-1]])

In [ ]:
arr[:,:-1]

In [ ]:
b1 = sess.run(hx, {x:arr[:,:-1]})

In [ ]:
labelScale.inverse_transform(b1)

In [ ]:
plt.plot(ydata)
plt.plot(sess.run(hx, {x:xdata}), 'r--')
plt.show()